### ISSUE TITLE
How do I use the pretrained model for training Cotatron?

### ISSUE THREAD

**Issue by McTi** [mindslab-ai/cotatron#13]
Thanks for sharing the pretrained model - but I can't get it working for training Cotatron. 

When I try simply resuming Cotatron training with the full model using the following command:

```
python cotatron_trainer.py -c config/global/config.yaml config/cota/config.yaml \
                           -g 0 -n my_runname -p pretrained_decoder_libritts_vctk_epoch652_15388cc.ckpt

```
I get mismatched key errors. This is kinda expected, as cotatron is instantiated within the Synthesizer
```
Missing key(s) in state_dict: "encoder.embedding.weight", 
Unexpected key(s) in state_dict: "cotatron.encoder.embedding.weight

```
I can workaround this by using torch load/save to write out only the Cotatron part of the model...

```
checkpoint = torch.load('original.ckpt', map_location='cpu')
model = Synthesizer(hparams).cuda()
model.load_state_dict(checkpoint['state_dict'])

model.eval()

torch.save({
            'state_dict': model.cotatron.state_dict(),
            }, 'cotatron.ckpt')

```
But when I try training with this cotatron-specific checkpoint (i.e. 'cotatron.ckpt') pytorch-lightning complains with this error...

`KeyError: 'Trying to restore training state but checkpoint contains only the model. This is probably due to "ModelCheckpoint.save_weights_only" being set to `True`.'
`

I've tried various other options for extracting and reusing Cotatron-specific parameters from the checkpoint, but it seems that pytorch-lightning doesn't support this. 

Were you able to get this to work? If so, could you describe how it's done.

Thanks!

**Comment by seungwonpark** [comment]
Hi, thanks for trying out our model.
Could you specify the working environment of yours? Especially, what was your pytorch-lightning version?

**Comment by McTi** [comment]
Thanks @seungwonpark. I'm using `pytorch-lightning==0.7.3`

I tried using `pytorch-lightning==0.7.1` but hit the same issue as #8

**Comment by seungwonpark** [comment]
I see, unfortunately I cannot figure out the cause of the problem at this point.
You might want to either:
- re-implement the Cotatron from scratch by yourself (in this case I can add a link to your project if you’re publicly releasing the code on GitHub)
- or simply wait for the code of Assem-VC to be released (which is further improved version of this project)

**Comment by McTi** [comment]
Okay, thanks.

**Comment by amelieyu1989** [comment]
> Thanks for sharing the pretrained model - but I can't get it working for training Cotatron.
> 
> When I try simply resuming Cotatron training with the full model using the following command:
> 
> ```
> python cotatron_trainer.py -c config/global/config.yaml config/cota/config.yaml \
>                            -g 0 -n my_runname -p pretrained_decoder_libritts_vctk_epoch652_15388cc.ckpt
> ```
> 
> I get mismatched key errors. This is kinda expected, as cotatron is instantiated within the Synthesizer
> 
> ```
> Missing key(s) in state_dict: "encoder.embedding.weight", 
> Unexpected key(s) in state_dict: "cotatron.encoder.embedding.weight
> ```
> 
> I can workaround this by using torch load/save to write out only the Cotatron part of the model...
> 
> ```
> checkpoint = torch.load('original.ckpt', map_location='cpu')
> model = Synthesizer(hparams).cuda()
> model.load_state_dict(checkpoint['state_dict'])
> 
> model.eval()
> 
> torch.save({
>             'state_dict': model.cotatron.state_dict(),
>             }, 'cotatron.ckpt')
> ```
> 
> But when I try training with this cotatron-specific checkpoint (i.e. 'cotatron.ckpt') pytorch-lightning complains with this error...
> 
> `KeyError: 'Trying to restore training state but checkpoint contains only the model. This is probably due to "ModelCheckpoint.save_weights_only" being set to `True`.' `
> 
> I've tried various other options for extracting and reusing Cotatron-specific parameters from the checkpoint, but it seems that pytorch-lightning doesn't support this.
> 
> Were you able to get this to work? If so, could you describe how it's done.
> 
> Thanks!

have you resolved this problem ?

**Comment by McTi** [comment]
> have you resolved this problem ?

No. I decided to wait for the Assem-VC code release.

**Comment by amelieyu1989** [comment]
would you share your cotatron pre-trained model using the open-source
dataset?

**Comment by McTi** [comment]
A link to the pretrained model is provided in the [Colab notebook](https://colab.research.google.com/drive/1L1sOs21l6CeU1Zavd5VMHGjo-aUUUGFp?usp=sharing#scrollTo=jLhJpCCCg7_W)

`gdown.download('https://drive.google.com/uc?id=1slbH0OSUHu7CMWK9aye93yH2JDpE4uZ2', 'pretrained_decoder_libritts_vctk_epoch652_15388cc.ckpt', quiet=False)
`
