### ISSUE TITLE
Clarification regarding the configuration of the MelGAN model

### ISSUE THREAD

**Issue by danieltum** [mindslab-ai/cotatron#14]
Dear Team,

Thank you very much for your work on this project.
I am experimenting with your codebase and trying to synthesize the converted speech with a MelGan vocoder which I trained from scratch on a custom dataset. I am using the official implementation, which is available here: 
https://github.com/descriptinc/melgan-neurips
The model is trained with the default parameters, except for the Mel frequencies, which I've set to mel_fmin=70, mel_fmax=8000, as described in the Cotatron paper.

Can you please confirm that this is the same MelGAN configuration, which you have used for training MelGAN on LibriTTS+VCTK?
If not, can you kindly describe the differences or point me to the correct GIT repo? 

Many thanks.

**Comment by seungwonpark** [comment]
Hi, the mel calculation script is shown in https://github.com/mindslab-ai/cotatron/blob/master/modules/mel.py, and the configuration is shown in https://github.com/mindslab-ai/cotatron/blob/master/config/global/default.yaml.

If you're using the https://github.com/descriptinc/melgan-neurips and fix `mel_fmin` and `mel_fmax` to match our settings, then things will work well. Hope that helps!

**Comment by danieltum** [comment]
Thank you!
