### ISSUE TITLE
한국어 dataset 에 관한 recipe / korean dataset model

### ISSUE THREAD

**Issue by hyejin428** [mindslab-ai/cotatron#4]
KSS 데이터셋으로 cotatron 학습을 하고 있는데 15kstep을 돌렸지만 alignment가 거의 잡히지 않습니다..
공개된 git code 만으로 KSS 데이터셋 학습이 가능한가요?
KSS 데이터셋 학습을 위한 recipe를 공개해주실 수 있으신가요?

I'm training cotatron with KSS dataset, and I've trained 15k steps, but I can barely get an alignment.
Is it possible to learn KSS dataset only with the released git code?
Could you share the recipe for learning KSS dataset?

**Comment by seungwonpark** [comment]
Hi, thank you for your interest in our model.

Did you make sure that you're appropriately pre-processing the Korean text?
Since our published code do not fully support the Korean pre-processing, you should implement it by yourself.

**Comment by hyejin428** [comment]
메일 답변 주셔서 감사합니다!
전처리는 다른 한국어 타코트론2들과 비슷하게 작업했는데..
다른 방식으로 해결한 것 같습니다..!
감사합니다 !

2020년 8월 18일 (화) 오후 4:54, Seungwon Park 박승원 <notifications@github.com>님이 작성:
