### ISSUE TITLE
Single Target Speaker

### ISSUE THREAD

**Issue by ghost** [mindslab-ai/cotatron#5]
Does the number of speakers seem to affect the quality?

**Comment by seungwonpark** [comment]
The total amount of training dataset matters; the more and diverse the dataset that you use, the better the quality will be.
Plus, training a VC decoder with only a single target speaker won't work.

**Comment by ghost** [comment]
> The total amount of training dataset matters; the more and diverse the dataset that you use, the better the quality will be.
> Plus, training a VC decoder with only a single target speaker won't work.

@seungwonpark In the [demo](https://mindslab-ai.github.io/cotatron/), you showed an example of KSS dataset, which only consists of a Korean single female speaker. Why does it work in that case?

**Comment by seungwonpark** [comment]
@capavrulus, thanks for asking.

In that case, the Korean Cotatron model was trained with a multi-speaker Korean TTS dataset. In other words, not only the KSS dataset was used for that, but also other speakers from our proprietary database were used.
